import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.6.0/firebase-app.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/11.6.0/firebase-auth.js';
import { getFirestore, collection, doc, getDoc, onSnapshot, orderBy, query, limit, serverTimestamp, updateDoc, setDoc, Timestamp } from 'https://www.gstatic.com/firebasejs/11.6.0/firebase-firestore.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/11.6.0/firebase-functions.js';
import { firebaseConfig } from './firebase-config.js';

const $ = id => document.getElementById(id);
const randomName = () => ['Sunny Fox','Blue Comet','Cosy Otter','Mellow Finch','Little Nova','Kind Panda'][Math.floor(Math.random()*6)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate = value => value?.toDate ? value.toDate().toLocaleString() : new Date(value).toLocaleString();
const expiresText = value => { const ms = (value?.toDate ? value.toDate() : new Date(value)).getTime() - Date.now(); if (ms <= 0) return 'Expired'; const days=Math.floor(ms/86400000), hours=Math.floor(ms%86400000/3600000), mins=Math.max(1,Math.floor(ms%3600000/60000)); return days ? `expires in ${days}d ${hours}h` : hours ? `expires in ${hours}h ${mins}m` : `expires in ${mins}m`; };
let db, auth, functions, user, activeRoom, activeMember, unsubs=[], roomToJoin, heartbeat, roomCache=[];
const call = name => httpsCallable(functions, name);
function note(id, text, type='') { const el=$(id); el.textContent=text; el.className=`note show ${type}`; }
function busy(value){$('loading').classList.toggle('show',value)}
function showView(which){$('home-view').classList.toggle('active',which==='home');$('room-view').classList.toggle('active',which==='room');$('home-button').hidden=which==='home';}
function cleanSubs(){unsubs.forEach(fn=>fn());unsubs=[];if(heartbeat)clearInterval(heartbeat);}
function errorText(error){const code=error?.code||''; if(code.includes('internal'))return 'The room function failed in Firebase. Check Firebase Console → Functions → Logs for the createRoom error.';if(code.includes('permission-denied'))return 'You do not have access to this room.'; if(code.includes('not-found'))return 'Room not found. Check the room code.'; if(code.includes('deadline-exceeded'))return 'The room has expired.'; return error?.message?.replace(/^FirebaseError:\s*/,'') || 'Something went wrong. Please try again.';}

async function start(){
  if(firebaseConfig.apiKey.startsWith('PASTE_') || firebaseConfig.projectId==='YOUR_PROJECT_ID') { $('connection').textContent='Firebase setup needed · see README'; $('room-list').innerHTML='<div class="empty">Add your Firebase project settings to firebase-config.js, then follow README.md to enable shared rooms.</div>'; return; }
  try{const app=initializeApp(firebaseConfig); auth=getAuth(app); db=getFirestore(app); functions=getFunctions(app); const credential=await signInAnonymously(auth); user=credential.user; $('connection').textContent='Connected · anonymous account'; await loadRooms();}
  catch(error){$('connection').textContent='Connection error';$('room-list').innerHTML=`<div class="empty">${esc(errorText(error))}. Check Firebase setup and authorized domains.</div>`;}
}

async function loadRooms(){
  await refreshRooms();
}
async function refreshRooms(){try{const result=await call('listRooms')({});roomCache=result.data.rooms||[];renderRooms();}catch(error){$('room-list').innerHTML=`<div class="empty">Could not load rooms: ${esc(errorText(error))}</div>`;}}
function renderRooms(){const wanted=$('room-search').value.trim().toUpperCase(),rooms=roomCache.filter(r=>r.expiresAt>Date.now()).filter(r=>!wanted||r.id.includes(wanted));$('room-list').innerHTML=rooms.length?rooms.map(r=>`<article class="room-card"><div class="room-info"><strong>${esc(r.name)}</strong><div class="room-meta">Code ${esc(r.id)} · hosted by ${esc(r.creatorName)} · created ${esc(formatDate(r.createdAt))}<br>${esc(expiresText(r.expiresAt))} · ${Number(r.memberCount||0)} member${Number(r.memberCount||0)===1?'':'s'} · ${r.hasPassword?'password required':'no password'}${r.description?` · ${esc(r.description)}`:''}</div></div><button class="btn small" data-join="${esc(r.id)}">Join</button></article>`).join(''):'<div class="empty">No active rooms found. Create one or try another code.</div>';document.querySelectorAll('[data-join]').forEach(b=>b.addEventListener('click',()=>openJoin(roomCache.find(r=>r.id===b.dataset.join))));}

async function createRoom(){
  const password=$('new-password').value; if(password&&password.length<4){note('create-note','If you add a password, use at least 4 characters.','error');return;}
  const minutes=Number($('new-expiry').value); if(!Number.isInteger(minutes)||minutes<1||minutes>43200){note('create-note','Expiry must be between 1 minute and 30 days (43,200 minutes).','error');return;}
  busy(true);try{const result=await call('createRoom')({name:$('new-room-name').value.trim(),creatorName:$('creator-name').value.trim()||randomName(),password,expiresMinutes:minutes,description:$('new-description').value.trim()});$('new-password').value='';await enterRoom(result.data.roomId,result.data.creatorName,'admin');}catch(error){note('create-note',errorText(error),'error');}finally{busy(false);}
}

function openJoin(room, justCreated=false){ if(!room)return; roomToJoin={...room,justCreated}; const needsPassword=room.hasPassword!==false;$('password-room-info').textContent=`${room.name||'This room'} · code ${room.id||room.roomId} · hosted by ${room.creatorName||'the room creator'} · ${room.expiresAt?expiresText(room.expiresAt):'new room'}`;$('password-label').hidden=!needsPassword;$('password-entry').hidden=!needsPassword;$('password-entry').required=needsPassword;$('join-modal-title').textContent=needsPassword?'Enter room password':'Join room';$('password-entry').value='';$('password-note').className='note';$('password-modal').classList.add('show');if(needsPassword)setTimeout(()=>$('password-entry').focus(),30); }
async function joinRoom(){if(!roomToJoin)return;busy(true);try{const result=await call('joinRoom')({roomId:roomToJoin.id||roomToJoin.roomId,password:$('password-entry').value,displayName:$('guest-name').value.trim()||randomName()});$('password-modal').classList.remove('show');await enterRoom(result.data.roomId,result.data.displayName,result.data.role);}catch(error){note('password-note',errorText(error),'error');}finally{busy(false);}}

async function enterRoom(roomId,displayName,role){
  cleanSubs();const snap=await getDoc(doc(db,'rooms',roomId));if(!snap.exists())throw new Error('Room not found.');activeRoom={id:roomId,...snap.data()};activeMember={displayName,role};
  showView('room');$('room-title').textContent=activeRoom.name;$('room-subtitle').textContent=`Created by ${activeRoom.creatorName} · ${expiresText(activeRoom.expiresAt)}`;$('room-code-label').textContent=`ROOM CODE ${roomId}`;updateRoomAbout();renderSettings();subscribeRoom();
  const invite=new URL(location.href);invite.search='';invite.hash='';invite.searchParams.set('room',roomId);history.replaceState({},'',invite);
}

function subscribeRoom(){
  unsubs.push(onSnapshot(doc(db,'rooms',activeRoom.id),snap=>{if(!snap.exists()||snap.data().expiresAt.toMillis()<=Date.now()){alert('This room has expired.');leaveRoom();return;}activeRoom={id:snap.id,...snap.data()};$('room-title').textContent=activeRoom.name;$('room-subtitle').textContent=`Created by ${activeRoom.creatorName} · ${expiresText(activeRoom.expiresAt)}`;updateRoomAbout();}));
  unsubs.push(onSnapshot(query(collection(db,'rooms',activeRoom.id,'messages'),orderBy('createdAt','desc'),limit(150)),snap=>{const box=$('messages'),wasBottom=box.scrollHeight-box.scrollTop-box.clientHeight<70;box.innerHTML=[...snap.docs].reverse().map(d=>{const m=d.data();if(m.kind==='event')return `<div class="event">${esc(m.text)}</div>`;return `<article class="message ${m.senderUid===user.uid?'mine':''}"><div class="msg-name">${esc(m.displayName)}${m.senderUid===activeRoom.creatorUid?' · host':''}</div><div class="bubble">${m.kind==='gif'?`<img src="${esc(m.gifUrl)}" alt="GIF shared by ${esc(m.displayName)}" loading="lazy">`:esc(m.text)}${m.kind==='gif'&&m.text?`<div>${esc(m.text)}</div>`:''}</div><div class="msg-time">${esc(m.createdAt?.toDate?.().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})||'sending…')}${activeMember.role==='admin'&&m.senderUid!==user.uid&&m.kind!=='event'?` · <button class="tool" data-delete="${esc(d.id)}">Delete</button>`:''}</div></article>`}).join('');if(wasBottom)box.scrollTop=box.scrollHeight;document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>deleteMessage(b.dataset.delete)));}));
  unsubs.push(onSnapshot(collection(db,'rooms',activeRoom.id,'members'),snap=>{const docs=snap.docs.map(d=>({id:d.id,...d.data()}));$('member-count').textContent=`(${docs.length})`;$('member-list').innerHTML=docs.map(m=>`<div class="member"><span>${esc(m.displayName)}${m.role==='admin'?' · host':''}</span><span class="${m.online?'online-dot':''}">${m.online?'● here':'away'}</span>${activeMember.role==='admin'&&m.id!==user.uid?`<button class="tool" data-block="${esc(m.id)}">Block</button>`:''}</div>`).join('');document.querySelectorAll('[data-block]').forEach(b=>b.addEventListener('click',()=>blockUser(b.dataset.block)));}));
  if(activeMember.role==='admin')unsubs.push(onSnapshot(query(collection(db,'rooms',activeRoom.id,'activity'),orderBy('createdAt','desc'),limit(40)),snap=>{$('activity-log').innerHTML=snap.docs.map(d=>{const a=d.data();return `<div>${esc(a.createdAt?.toDate?.().toLocaleString()||'')} · ${esc(a.text)}</div>`}).join('')||'<div>No activity yet.</div>';}));
  const memberRef=doc(db,'rooms',activeRoom.id,'members',user.uid);const markOnline=()=>updateDoc(memberRef,{online:true,lastSeen:serverTimestamp()}).catch(()=>{});markOnline();heartbeat=setInterval(markOnline,45000);
}
function updateRoomAbout(){$('about-room').textContent=[activeRoom.description||'No description added.',activeRoom.rules?`Room rules: ${activeRoom.rules}`:''].filter(Boolean).join('\n\n');}

function renderSettings(){const isAdmin=activeMember.role==='admin';$('settings-area').innerHTML=`${isAdmin?`<details><summary>Room settings</summary><label class="label">ROOM NAME</label><input class="input" id="setting-name" maxlength="48" value="${esc(activeRoom.name)}"><label class="label">DESCRIPTION</label><textarea class="textarea" id="setting-description" maxlength="180">${esc(activeRoom.description||'')}</textarea><label class="label">ROOM RULES</label><textarea class="textarea" id="setting-rules" maxlength="500" placeholder="Add a few guidelines">${esc(activeRoom.rules||'')}</textarea><label class="label">DELETE AFTER (MINUTES, MAX 43,200)</label><input class="input" id="setting-expiry" type="number" min="1" max="43200" value="${Math.max(1,Math.round((activeRoom.expiresAt.toMillis()-activeRoom.createdAt.toMillis())/60000))}"><button class="btn small full" id="save-settings">Save room settings</button><label class="label">ROOM PASSWORD (LEAVE BLANK TO REMOVE)</label><input class="input" id="setting-password" type="password" placeholder="New password, or blank for none"><button class="btn secondary small full" id="save-password">Set / remove password</button><label class="label">MAKE A MEMBER ADMIN</label><select class="input" id="promote-member"><option value="">Choose a member</option></select><button class="btn secondary small full" id="promote-button">Nominate admin</button><div class="note" id="settings-note"></div><details><summary>Admin activity log</summary><div class="activity" id="activity-log">Loading…</div></details></details>`:`<p>You are a guest in this room. Room settings are managed by the host.</p>`}`;
  if(!isAdmin)return;
  $('save-settings').addEventListener('click',saveSettings);$('save-password').addEventListener('click',savePassword);$('promote-button').addEventListener('click',promoteAdmin);
  onSnapshot(collection(db,'rooms',activeRoom.id,'members'),snap=>{const select=$('promote-member');if(!select)return;select.innerHTML='<option value="">Choose a member</option>'+snap.docs.filter(d=>d.id!==user.uid).map(d=>`<option value="${esc(d.id)}">${esc(d.data().displayName)}</option>`).join('');});
}
async function saveSettings(){const minutes=Number($('setting-expiry').value);if(!Number.isInteger(minutes)||minutes<1||minutes>43200){note('settings-note','Expiry must be 1 to 43,200 minutes.','error');return;}try{const out=await call('updateRoom')({roomId:activeRoom.id,name:$('setting-name').value.trim(),description:$('setting-description').value.trim(),rules:$('setting-rules').value.trim(),expiresMinutes:minutes});activeRoom={...activeRoom,...out.data,expiresAt:Timestamp.fromMillis(out.data.expiresAtMillis)};$('room-title').textContent=activeRoom.name;updateRoomAbout();$('room-subtitle').textContent=`Created by ${activeRoom.creatorName} · ${expiresText(activeRoom.expiresAt)}`;note('settings-note','Room settings saved.','success');}catch(e){note('settings-note',errorText(e),'error');}}
async function savePassword(){const password=$('setting-password').value;if(password&&password.length<4){note('settings-note','Use at least 4 characters, or leave it blank to remove the password.','error');return;}try{await call('setRoomPassword')({roomId:activeRoom.id,password});$('setting-password').value='';note('settings-note',password?'Room password set.':'Room password removed.','success');}catch(e){note('settings-note',errorText(e),'error');}}
async function promoteAdmin(){const targetUid=$('promote-member').value;if(!targetUid){note('settings-note','Choose a room member first.','error');return;}try{await call('promoteAdmin')({roomId:activeRoom.id,targetUid});note('settings-note','Admin role updated.','success');}catch(e){note('settings-note',errorText(e),'error');}}
async function blockUser(targetUid){if(!confirm('Block this person from rejoining this room?'))return;try{await call('blockUser')({roomId:activeRoom.id,targetUid});}catch(e){alert(errorText(e));}}
async function deleteMessage(messageId){if(!confirm('Delete this message for everyone?'))return;try{await call('deleteMessage')({roomId:activeRoom.id,messageId});}catch(e){alert(errorText(e));}}

async function sendMessage(){const text=$('message-input').value.trim();if(!text)return;if(text.length>255)return;try{await setDoc(doc(collection(db,'rooms',activeRoom.id,'messages')),{senderUid:user.uid,displayName:activeMember.displayName,kind:'text',text,createdAt:serverTimestamp()});$('message-input').value='';updateCount();}catch(e){alert(errorText(e));}}
async function sendGif(){const url=prompt('Paste a direct GIF URL (must end in .gif, or use a trusted GIF link):');if(!url)return;let parsed;try{parsed=new URL(url)}catch{alert('Enter a valid HTTPS URL.');return;}if(parsed.protocol!=='https:'||url.length>500){alert('GIF link must be HTTPS and under 500 characters.');return;}const caption=prompt('Add an optional caption (up to 255 characters):')||'';if(caption.length>255){alert('Caption must be 255 characters or fewer.');return;}try{await setDoc(doc(collection(db,'rooms',activeRoom.id,'messages')),{senderUid:user.uid,displayName:activeMember.displayName,kind:'gif',text:caption,gifUrl:url,createdAt:serverTimestamp()});}catch(e){alert(errorText(e));}}
function updateCount(){$('message-count').textContent=`${$('message-input').value.length} / 255`;}
async function leaveRoom(){if(!activeRoom)return;try{await call('leaveRoom')({roomId:activeRoom.id});}catch{}cleanSubs();activeRoom=null;activeMember=null;history.replaceState({},'',location.pathname);showView('home');}

$('create-room').addEventListener('click',createRoom);$('refresh-rooms').addEventListener('click',refreshRooms);$('room-search').addEventListener('input',renderRooms);$('cancel-join').addEventListener('click',()=>$('password-modal').classList.remove('show'));$('confirm-join').addEventListener('click',joinRoom);$('password-entry').addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom();});$('home-button').addEventListener('click',leaveRoom);$('leave-room').addEventListener('click',leaveRoom);$('send-message').addEventListener('click',sendMessage);$('message-input').addEventListener('input',updateCount);$('message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}});$('gif-button').addEventListener('click',sendGif);$('copy-invite').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);$('copy-invite').textContent='Copied!';setTimeout(()=>$('copy-invite').textContent='Copy invite',1300);}catch{alert('Copy this invite URL from your browser address bar.');}});
const emojis=['😀','😂','🥹','😍','😎','🙌','👏','❤️','✨','🎉','🤔','👀','🔥','👍','🙏','💜','🌈','☕','🎈','💯'];$('emoji-tray').innerHTML=emojis.map(e=>`<button type="button">${e}</button>`).join('');$('emoji-toggle').addEventListener('click',()=>$('emoji-tray').classList.toggle('show'));$('emoji-tray').addEventListener('click',e=>{if(e.target.tagName==='BUTTON'){const input=$('message-input');input.value=(input.value+e.target.textContent).slice(0,255);updateCount();input.focus();}});
window.addEventListener('beforeunload',()=>{if(activeRoom)updateDoc(doc(db,'rooms',activeRoom.id,'members',user.uid),{online:false,lastSeen:serverTimestamp()});});
const inviteCode=new URLSearchParams(location.search).get('room');start().then(()=>{if(inviteCode&&db)getDoc(doc(db,'rooms',inviteCode.toUpperCase())).then(s=>{if(s.exists())openJoin({id:s.id,...s.data()});});});
