const $ = id => document.getElementById(id);
const randomName = () => ['Sunny Fox','Blue Comet','Cosy Otter','Mellow Finch','Little Nova','Kind Panda'][Math.floor(Math.random()*6)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate = v => new Date(v).toLocaleString();
const expiresText = v => { const ms = new Date(v).getTime()-Date.now(); if(ms<=0)return 'Expired';const d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.max(1,Math.floor(ms%3600000/60000));return d?`expires in ${d}d ${h}h`:h?`expires in ${h}h ${m}m`:`expires in ${m}m`; };
const getVisitor = () => { let id=localStorage.getItem('gather-visitor');if(!id){id=crypto.randomUUID();localStorage.setItem('gather-visitor',id)}return id; };
const visitorId=getVisitor();let activeRoom=null,activeMember=null,roomToJoin=null,pollTimer=null,roomCache=[],syncBusy=false;
const adminKey=id=>localStorage.getItem(`gather-admin-${id}`)||'';
async function api(path, options={}) { const headers={'Content-Type':'application/json','X-Visitor-Id':visitorId,...(options.headers||{})};const match=path.match(/^rooms\/([^/]+)/);if(match){const key=adminKey(match[1]);if(key)headers['X-Admin-Key']=key}const res=await fetch(`/api/${path}`,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data; }
function note(id,text,type=''){const el=$(id);el.textContent=text;el.className=`note show ${type}`}
function busy(v){$('loading').classList.toggle('show',v)}
function showView(which){$('home-view').classList.toggle('active',which==='home');$('room-view').classList.toggle('active',which==='room');$('home-button').hidden=which==='home'}
function errorText(e){return e?.message||'Something went wrong. Please try again.'}
function cleanSubs(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
async function start(){ $('connection').textContent='Connected · Cloudflare';try{await refreshRooms()}catch(e){$('room-list').innerHTML=`<div class="empty">Could not connect: ${esc(errorText(e))}. Finish the Cloudflare setup in README.md.</div>`;} }
async function refreshRooms(){try{const r=await api('rooms');roomCache=r.rooms||[];renderRooms()}catch(e){$('room-list').innerHTML=`<div class="empty">Could not load rooms: ${esc(errorText(e))}</div>`}}
function renderRooms(){const code=$('room-filter-code').value.trim().toUpperCase(),host=$('room-filter-creator').value.trim().toLowerCase(),date=$('room-filter-date').value;const rooms=roomCache.filter(r=>{const created=new Date(r.createdAt).toISOString().slice(0,10);return(!code||r.id.includes(code)||r.name.toLowerCase().includes(code.toLowerCase()))&&(!host||r.creatorName.toLowerCase().includes(host))&&(!date||created===date)});$('room-list').innerHTML=rooms.length?rooms.map(r=>`<article class="room-card"><div class="room-info"><strong>${esc(r.name)}</strong><div class="room-meta"><b>Code ${esc(r.id)}</b> · host ${esc(r.creatorName)} · ${esc(formatDate(r.createdAt))}<br>${esc(expiresText(r.expiresAt))} · ${Number(r.memberCount||0)} member${Number(r.memberCount)===1?'':'s'} · ${r.hasPassword?'password required':'open access'}</div></div><button class="btn small" data-join="${esc(r.id)}">Join</button></article>`).join(''):'<div class="empty">No active rooms match those filters.</div>';document.querySelectorAll('[data-join]').forEach(b=>b.addEventListener('click',()=>openJoin(roomCache.find(r=>r.id===b.dataset.join))))}
async function joinByCode(){const id=$('room-code-entry').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(id)){note('join-note','Enter the 6-character room code.','error');return}busy(true);try{const r=await api(`rooms/${id}`);if(!r.room)throw new Error('Room not found or expired.');openJoin(r.room);$('join-note').className='note'}catch(e){note('join-note',errorText(e),'error')}finally{busy(false)}}
async function createRoom(){const password=$('new-password').value;const minutes=Number($('new-expiry').value);if(password&&password.length<4){note('create-note','Password must be at least 4 characters.','error');return}if(!Number.isInteger(minutes)||minutes<1||minutes>43200){note('create-note','Expiry must be between 1 minute and 30 days.','error');return}busy(true);try{const r=await api('rooms',{method:'POST',body:JSON.stringify({name:$('new-room-name').value.trim(),creatorName:$('creator-name').value.trim()||randomName(),password,expiresMinutes:minutes,description:$('new-description').value.trim()})});localStorage.setItem(`gather-admin-${r.room.id}`,r.adminKey);$('new-password').value='';alert(`Room created: ${r.room.id}\n\nAdmin password (save it somewhere safe):\n${r.adminKey}\n\nIt is saved in this browser too.`);await enterRoom({room:r.room,member:{displayName:r.room.creatorName,role:'admin'}})}catch(e){note('create-note',errorText(e),'error')}finally{busy(false)}}
function openJoin(room){if(!room)return;roomToJoin=room;const needs=!!room.hasPassword;$('password-room-info').textContent=`${room.name} · code ${room.id} · hosted by ${room.creatorName} · ${expiresText(room.expiresAt)}`;$('password-label').hidden=!needs;$('password-entry').hidden=!needs;$('password-entry').required=needs;$('join-modal-title').textContent=needs?'Enter room password':'Join room';$('password-entry').value='';$('guest-name').value='';$('admin-password').value='';$('password-note').className='note';$('password-modal').classList.add('show')}
async function joinRoom(){if(!roomToJoin)return;busy(true);try{const adminPass=$('admin-password').value;const r=await api(`rooms/${roomToJoin.id}/join`,{method:'POST',headers:adminPass?{'X-Admin-Key':adminPass}:{},body:JSON.stringify({password:$('password-entry').value,displayName:$('guest-name').value.trim()||randomName()})});if(adminPass)localStorage.setItem(`gather-admin-${r.room.id}`,adminPass);$('password-modal').classList.remove('show');await enterRoom(r)}catch(e){note('password-note',errorText(e),'error')}finally{busy(false)}}
async function enterRoom(result){cleanSubs();activeRoom=result.room;activeMember=result.member;showView('room');renderSettings();updateRoom(result.room);await syncRoom();pollTimer=setInterval(syncRoom,10000);const invite=new URL(location.href);invite.search='';invite.hash='';invite.searchParams.set('room',result.room.id);history.replaceState({},'',invite)}
function updateRoom(r){activeRoom=r;$('room-title').textContent=r.name;$('room-subtitle').textContent=`Created by ${r.creatorName} · ${expiresText(r.expiresAt)}`;$('room-code-label').textContent=`ROOM CODE ${r.id}`;$('about-room').textContent=[r.description||'No description added.',r.rules?`Room rules: ${r.rules}`:''].filter(Boolean).join('\n\n')}
async function syncRoom(){if(!activeRoom||syncBusy)return;syncBusy=true;try{const r=await api(`rooms/${activeRoom.id}`);updateRoom(r.room);renderChat(r.messages||[]);renderMembers(r.members||[]);if(activeMember.role==='admin')renderActivity(r.activity||[])}catch(e){if(/expired|not found|blocked|403/i.test(errorText(e))){alert(errorText(e));leaveRoom(false)}}finally{syncBusy=false}}
function renderChat(messages){const box=$('messages'),bottom=box.scrollHeight-box.scrollTop-box.clientHeight<70;box.innerHTML=messages.map(m=>m.kind==='event'?`<div class="event">${esc(m.text)}</div>`:`<article class="message ${m.senderId===visitorId?'mine':''}"><div class="msg-name">${esc(m.displayName)}${m.role==='admin'?' · host':''}</div><div class="bubble">${m.kind==='gif'?`<img src="${esc(m.gifUrl)}" alt="Shared GIF" loading="lazy">`:esc(m.text)}${m.kind==='gif'&&m.text?`<div>${esc(m.text)}</div>`:''}</div><div class="msg-time">${esc(new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}))}${activeMember.role==='admin'&&m.kind!=='event'?` · <button class="tool" data-delete="${esc(m.id)}">Delete</button>`:''}</div></article>`).join('');if(bottom)box.scrollTop=box.scrollHeight;document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteMessage(b.dataset.delete))}
function renderMembers(members){$('member-count').textContent=`(${members.length})`;$('member-list').innerHTML=members.map(m=>{const online=Date.now()-m.lastSeen<30000;return `<div class="member"><span>${esc(m.displayName)}${m.role==='admin'?' · host':''}</span><span class="${online?'online-dot':''}">${online?'● here':'away'}</span>${activeMember.role==='admin'&&m.visitorId!==visitorId?`<button class="tool" data-block="${esc(m.visitorId)}">Block</button>`:''}</div>`}).join('');document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>blockUser(b.dataset.block));const sel=$('promote-member');if(sel)sel.innerHTML='<option value="">Choose a member</option>'+members.filter(m=>m.visitorId!==visitorId).map(m=>`<option value="${esc(m.visitorId)}">${esc(m.displayName)}</option>`).join('')}
function renderActivity(items){const log=$('activity-log');if(log)log.innerHTML=items.map(a=>`<div>${esc(formatDate(a.createdAt))} · ${esc(a.text)}</div>`).join('')||'<div>No activity yet.</div>'}
function renderSettings(){const admin=activeMember.role==='admin';$('settings-area').innerHTML=admin?`<details><summary>Room settings</summary><label class="label">ROOM NAME</label><input class="input" id="setting-name" maxlength="48"><label class="label">DESCRIPTION</label><textarea class="textarea" id="setting-description" maxlength="180"></textarea><label class="label">ROOM RULES</label><textarea class="textarea" id="setting-rules" maxlength="500"></textarea><label class="label">DELETE AFTER (MINUTES, MAX 43,200)</label><input class="input" id="setting-expiry" type="number" min="1" max="43200"><button class="btn small full" id="save-settings">Save room settings</button><label class="label">ROOM PASSWORD (BLANK REMOVES IT)</label><input class="input" id="setting-password" type="password" placeholder="New password, or blank for none"><button class="btn secondary small full" id="save-password">Set / remove password</button><label class="label">MAKE A MEMBER ADMIN</label><select class="input" id="promote-member"><option value="">Choose a member</option></select><button class="btn secondary small full" id="promote-button">Nominate admin</button><div class="note" id="settings-note"></div><details><summary>Admin activity log</summary><div class="activity" id="activity-log">Loading…</div></details></details>`:'<p>You are a guest in this room. Room settings are managed by the host.</p>';if(!admin)return;$('setting-name').value=activeRoom.name;$('setting-description').value=activeRoom.description||'';$('setting-rules').value=activeRoom.rules||'';$('setting-expiry').value=Math.max(1,Math.ceil((new Date(activeRoom.expiresAt)-Date.now())/60000));$('save-settings').onclick=saveSettings;$('save-password').onclick=savePassword;$('promote-button').onclick=promoteAdmin}
async function saveSettings(){const minutes=Number($('setting-expiry').value);if(!Number.isInteger(minutes)||minutes<1||minutes>43200){note('settings-note','Expiry must be 1 to 43,200 minutes.','error');return}try{const r=await api(`rooms/${activeRoom.id}/settings`,{method:'PATCH',body:JSON.stringify({name:$('setting-name').value.trim(),description:$('setting-description').value.trim(),rules:$('setting-rules').value.trim(),expiresMinutes:minutes})});updateRoom(r.room);note('settings-note','Settings saved.','success')}catch(e){note('settings-note',errorText(e),'error')}}
async function savePassword(){try{await api(`rooms/${activeRoom.id}/password`,{method:'PUT',body:JSON.stringify({password:$('setting-password').value})});$('setting-password').value='';note('settings-note','Password updated.','success')}catch(e){note('settings-note',errorText(e),'error')}}
async function promoteAdmin(){const targetId=$('promote-member').value;if(!targetId)return note('settings-note','Choose a room member first.','error');try{const r=await api(`rooms/${activeRoom.id}/admins`,{method:'POST',body:JSON.stringify({targetId})});alert(`Share this one-time admin password with ${r.displayName}:\n\n${r.adminKey}`);note('settings-note','New admin password created. Share it privately with that member.','success')}catch(e){note('settings-note',errorText(e),'error')}}
async function blockUser(targetId){if(!confirm('Block this person from rejoining this room?'))return;try{await api(`rooms/${activeRoom.id}/block`,{method:'POST',body:JSON.stringify({targetId})});syncRoom()}catch(e){alert(errorText(e))}}
async function deleteMessage(messageId){if(!confirm('Delete this message for everyone?'))return;try{await api(`rooms/${activeRoom.id}/messages/${messageId}`,{method:'DELETE'});syncRoom()}catch(e){alert(errorText(e))}}
async function sendMessage(){const text=$('message-input').value.trim();if(!text)return;if(text.length>255)return;try{await api(`rooms/${activeRoom.id}/messages`,{method:'POST',body:JSON.stringify({text,kind:'text'})});$('message-input').value='';updateCount();syncRoom()}catch(e){alert(errorText(e))}}
async function sendGif(){const url=prompt('Paste a direct GIF URL (HTTPS).');if(!url)return;try{const p=new URL(url);if(p.protocol!=='https:'||url.length>500)throw new Error('GIF link must be HTTPS and under 500 characters.')}catch(e){alert(e.message||'Enter a valid HTTPS URL.');return}const text=prompt('Optional caption (up to 255 characters):')||'';if(text.length>255)return alert('Caption must be 255 characters or fewer.');try{await api(`rooms/${activeRoom.id}/messages`,{method:'POST',body:JSON.stringify({kind:'gif',gifUrl:url,text})});syncRoom()}catch(e){alert(errorText(e))}}
function updateCount(){$('message-count').textContent=`${$('message-input').value.length} / 255`}
async function leaveRoom(send=true){if(!activeRoom)return;const id=activeRoom.id;try{cleanSubs();if(send)await api(`rooms/${id}/leave`,{method:'POST',body:'{}'})}catch{}activeRoom=null;activeMember=null;history.replaceState({},'',location.pathname);showView('home');await refreshRooms()}
$('create-room').onclick=createRoom;$('refresh-rooms').onclick=refreshRooms;$('join-code-button').onclick=joinByCode;$('room-code-entry').onkeydown=e=>{if(e.key==='Enter')joinByCode()};$('room-filter-code').oninput=renderRooms;$('room-filter-creator').oninput=renderRooms;$('room-filter-date').onchange=renderRooms;$('clear-filters').onclick=()=>{$('room-filter-code').value='';$('room-filter-creator').value='';$('room-filter-date').value='';renderRooms()};$('cancel-join').onclick=()=>$('password-modal').classList.remove('show');$('confirm-join').onclick=joinRoom;$('password-entry').onkeydown=e=>{if(e.key==='Enter')joinRoom()};$('home-button').onclick=()=>leaveRoom();$('leave-room').onclick=()=>leaveRoom();$('send-message').onclick=sendMessage;$('message-input').oninput=updateCount;$('message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}};$('gif-button').onclick=sendGif;$('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('copy-invite').textContent='Copied!';setTimeout(()=>$('copy-invite').textContent='Copy invite',1300)}catch{alert('Copy the invite URL from your browser address bar.')}};
const emojis=['😀','😂','🥹','😍','😎','🙌','👏','❤️','✨','🎉','🤔','👀','🔥','👍','🙏','💜','🌈','☕','🎈','💯'];$('emoji-tray').innerHTML=emojis.map(e=>`<button type="button">${e}</button>`).join('');$('emoji-toggle').onclick=()=>$('emoji-tray').classList.toggle('show');$('emoji-tray').onclick=e=>{if(e.target.tagName==='BUTTON'){const i=$('message-input');i.value=(i.value+e.target.textContent).slice(0,255);updateCount();i.focus()}};
start().then(()=>{const id=new URLSearchParams(location.search).get('room');if(id)api(`rooms/${id}`).then(r=>openJoin(r.room)).catch(()=>{})});
